# Copyright (c) 2021 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
      
    # Add a new remote for the forked Zephyr repository with milkv-duo support
    - name: xingrz-zephyr 
      url-base: https://github.com/xingrz

  projects:
    - name: zephyr
      remote: xingrz-zephyr
      revision: refs/heads/milkv-duo/hwmv2/dev
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - open-amp
          - libmetal
